### Retrieve all the movies

GET http://localhost:1234/movies

### Retrieve a movie from its ID

GET http://localhost:1234/movies/a7d9475e-5967-11ee-8c92-3984ea0a6f13

### Delete a movie from it ID

DELETE http://localhost:1234/movies/8c1f743c-5c7f-11ee-80f9-b4e55e28aff6

### Retrieve all the movies from a genre

GET http://localhost:1234/movies?genre=Sci-Fi

### Create a new movie

POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "Oppenheimer",
    "year": 2023,
    "director": "Christopher Nolan",
    "duration": 180,
    "poster": "https://www.imdb.com/title/tt15398776/mediaviewer/rm2670601217/?ref_=tt_ov_i",
    "genre": ["Biography", "Drama", "History"],
    "rate": 8.6
}

### Update a movie

PATCH http://localhost:1234/movies/a7d9475e-5967-11ee-8c92-3984ea0a6f13
Content-Type: application/json

{
  "rate": 9.0  
}